Refactored to support multiple named instances.
This introduces a new tag ResourceName on EC2 instances and
the necessary changes to the various commands.

diff --git a/snapshot b/snapshot
--- a/snapshot
+++ b/snapshot
@@ -1,16 +1,22 @@
 #!/bin/bash
 
-IMAGE_NAME=$1
+INSTANCE_NAME=$1
+IMAGE_NAME=$2
 
-if [ -z $IMAGE_NAME ]; then
-  echo "Usage: snapshot <image name>"
+if [[ -z $IMAGE_NAME || -z $INSTANCE_NAME ]]; then
+  echo "Usage: snapshot <your name of instance> <image name>"
   exit 1
 fi
 
 STACK_NAME=devbox
 
 # Running instances with tag Application=devbox
-INSTANCE_ID=$(aws --profile devbox ec2 describe-instances --filters "Name=tag:Application,Values=devbox" "Name=instance-state-code,Values=16" | jq -r '.Reservations[].Instances[].InstanceId')
+INSTANCE_ID=$(aws --profile devbox ec2 describe-instances --filters "Name=tag:Application,Values=devbox" "Name=tag:ResourceName,Values=$INSTANCE_NAME" "Name=instance-state-code,Values=16" | jq -r '.Reservations[].Instances[].InstanceId')
+
+if [ -z $INSTANCE_ID ]; then
+  echo "Failed: No running instances named '$INSTANCE_NAME'."
+  exit 1
+fi
 
 if (( $(grep -c . <<<"$INSTANCE_ID") > 1 )); then 
   echo "Failed: Multiple instances are running:"
diff --git a/up b/up
--- a/up
+++ b/up
@@ -1,10 +1,12 @@
 #!/bin/bash
 
+STACK_NAME=devbox
 IMAGE_NAME=$1
-INSTANCE_TYPE=$2
+INSTANCE_NAME=$2
+INSTANCE_TYPE=$3
 
-if [ -z $IMAGE_NAME ]; then
-  echo "Usage: up <image name>"
+if [[ -z $IMAGE_NAME || -z $INSTANCE_NAME ]]; then
+  echo "Usage: up <image name> <your name for this instance> [instance type]"
   exit 1
 fi
 
@@ -12,11 +14,15 @@ if [ -z $INSTANCE_TYPE ]; then
   INSTANCE_TYPE="t2.micro"
 fi
 
-STACK_NAME=devbox
 
 STACKINFO=$(aws --profile devbox cloudformation describe-stacks | jq ".Stacks[] | select(.StackName==\"$STACK_NAME\") | .Outputs")
 
 IMAGE_ID=$(aws --profile devbox ec2 describe-images --filters "Name=tag:Application,Values=devbox" "Name=name,Values=$IMAGE_NAME" | jq -r .Images[].ImageId)
+
+if [ -z $IMAGE_ID ]; then
+  echo "Failed: Image $IMAGE_NAME not found."
+  exit 1
+fi
 
 if (( $(grep -c . <<<"$IMAGE_ID") > 1 )); then 
   echo "Failed: Multiple images named '$IMAGE_NAME':"
@@ -28,11 +34,11 @@ SECURITY_GROUP=$(echo $STACKINFO | jq -r '.[] | select(.OutputKey=="SecurityGrou
 SUBNET=$(echo $STACKINFO | jq -r '.[] | select(.OutputKey=="Subnet") | .OutputValue')
 
 INSTANCE_ID=$(aws --profile devbox ec2 run-instances --image-id $IMAGE_ID --count 1 --instance-type $INSTANCE_TYPE --key-name $STACK_NAME --security-group-ids $SECURITY_GROUP --subnet-id $SUBNET --associate-public-ip-address | jq -r '.Instances[0].InstanceId')
-aws --profile devbox ec2 create-tags --resources $INSTANCE_ID --tags Key=Application,Value=$STACK_NAME
+aws --profile devbox ec2 create-tags --resources $INSTANCE_ID --tags Key=Application,Value=$STACK_NAME Key=ResourceName,Value=$INSTANCE_NAME
 
 echo "Booting instance $INSTANCE_ID from image $IMAGE_ID..."
 
-aws --profile devbox ec2 wait instance-running --instance-ids $INSTANCE_ID
+aws --profile $STACK_NAME ec2 wait instance-running --instance-ids $INSTANCE_ID
 
 IP_ADDRESS=$(aws --profile devbox ec2 describe-instances --instance-ids $INSTANCE_ID | jq -r .Reservations[].Instances[].PublicIpAddress)
 
